title: Matematikk.wiki 
description: Leksikon for matematikk 

# Remote Setting
url: ""

# Theme
theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs


url: https://just-the-docs.github.io

aux_links:
  Github: https://github.com/Simon-Bakken-Jantasuk/matematikk-wiki

footer_content: 'Copyright &copy; 2023-<script> 
  let year = new Date().getFullYear();
  document.write(year);
  console.log("Success");
  </script> Simon Bakken-Jantasuk'

collections:
  Ungdomskole:
    permalink: "/:collection/:path/"
    output: true
  VGS:
    permalink: "/:collection/:path/"
    output: true
  Universitet:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    Ungdomskole:
      name: Ungdomskole 
    VGS:
      name: VGS
    Universitet:
      name: Universitet

# For copy button on code
enable_copy_code_button: true

callouts:
  warning:
    title: OBS! 
    color: red
  highlight:
    color: purple
  note:
    title: Bemerk
    color: blue
